#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/heart

PRODUCT_COPY_FILES += \
    vendor/lenovo/heart/proprietary/recovery/root/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/goodix_cfg_group.bin \
    vendor/lenovo/heart/proprietary/recovery/root/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/goodix_firmware.bin \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Bluetooth_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Codec_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_General_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Global_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Handset_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Hdmi_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Headset_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_Speaker_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/CDP/CDP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/CDP/CDP_workspaceFile.qwsp \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Codec_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Codec_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/lenovo/heart/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/lenovo/heart/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/lenovo/heart/proprietary/vendor/etc/camera/camxoverridesettings_for_cts.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings_for_cts.txt \
    vendor/lenovo/heart/proprietary/vendor/etc/init/android.hardware.camera.provider@2.4-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.4-service_64.rc \
    vendor/lenovo/heart/proprietary/vendor/etc/init/android.hardware.sensors@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@2.0-service.rc \
    vendor/lenovo/heart/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/lenovo/heart/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm4x6xx_0.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/msmnile_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msmnile_ak991x_0.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/msmnile_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msmnile_icm4x6xx_0.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/msmnile_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msmnile_irq.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/msmnile_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msmnile_power_0.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/msmnile_tmd3702.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msmnile_tmd3702.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/msmnile_tsl2584.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msmnile_tsl2584.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/tmd3702.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd3702.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/config/tsl2584.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tsl2584.json \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lenovo/heart/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lenovo/heart/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-cali.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-music.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-music.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-music.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-ringtone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-ringtone.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-ringtone.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-ringtone.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-voice.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-voice.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-dsp1-sp-voice.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-sp-voice.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs35l41-firmware-version.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-firmware-version.txt \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs47l35-dsp2-karaoke-music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs47l35-dsp2-karaoke-music.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs47l35-dsp2-karaoke-music.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs47l35-dsp2-karaoke-music.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs47l35-dsp3-ez2-record.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs47l35-dsp3-ez2-record.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs47l35-dsp3-ez2-record.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs47l35-dsp3-ez2-record.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs47l35-dsp3-karaoke-vocals.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs47l35-dsp3-karaoke-vocals.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/cs47l35-dsp3-karaoke-vocals.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs47l35-dsp3-karaoke-vocals.wmfw \
    vendor/lenovo/heart/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/lenovo/heart/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_imx519.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_imx576.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_imx576.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_ov8356.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_ov8356.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_s5k3p9sx.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_s5k3p9sx.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_imx519.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_imx576.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_imx576.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_ov8356.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_ov8356.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_s5k3p9sx.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_s5k3p9sx.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/lenovo/heart/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.sensormodule.ofilm_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ofilm_imx519.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.sensormodule.ofilm_imx576.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ofilm_imx576.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.sensormodule.ofilm_ov8356.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ofilm_ov8356.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.sensormodule.ofilm_s5k3p9sx.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ofilm_s5k3p9sx.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.tuned.ofilm_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.ofilm_imx519.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.tuned.ofilm_imx576.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.ofilm_imx576.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.tuned.ofilm_ov8356.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.ofilm_ov8356.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/com.qti.tuned.ofilm_s5k3p9sx.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.ofilm_s5k3p9sx.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/lenovo/heart/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    android.hardware.camera.provider@2.4-external \
    android.hardware.camera.provider@2.4-legacy \
    android.hardware.sensors@2.0-impl \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    camera.device@3.5-external-impl \
    camera.device@3.5-impl \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx576 \
    com.qti.sensor.ov8356 \
    com.qti.sensor.s5k3p9sx \
    com.arcsoft.node.capturebokeh \
    com.arcsoft.node.realtimebokeh \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper \
    android.hardware.camera.provider@2.4-impl \
    audio.primary.msmnile \
    camera.qcom \
    com.qti.chi.override \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    libadsprpc \
    libarcsoft_dualcam_refocus \
    libcamera_nn_stub \
    libcamxfdalgov7 \
    libcamxfdalgov8 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcom.qti.chinodeutils \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmpbase \
    libsensorcal \
    libsensorslog \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsns_registry_skel \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    libssc_default_listener \
    libswregistrationalgo \
    sensors.ssc \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.audiohalext@1.0-impl \
    liba2dpoffload \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadm \
    libaudcal \
    libaudio_log_utils \
    libaudioconfigstore \
    libpn553_fw \
    libqtigef \
    libssrec \
    libvideoutils \
    libasphere \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    libswdap \
    vendor.qti.hardware.audiohalext@1.0 \
    fingerprint.goodix_fod.msmnile \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    android.hardware.camera.provider@2.4-service_64 \
    android.hardware.sensors@2.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    sensors.qti \
    sscrpcd
